### ISSUE TITLE
 "Error: Cannot find module 'puppeteer-core/lib/cjs/common/Browser'"

### ISSUE THREAD

**Issue by metart43** [shelfio/chrome-aws-lambda-layer#21]
I am trying to use the layer in my personal project but keep getting an error
` \"Error: Cannot find module 'puppeteer-core/lib/cjs/common/Browser'"`
I feel like I am missing something, I have tried multiple solutions mentioned in the issue below, but it didn't help:
[I tried this downgrading puppeteer-core@4.0.1](https://github.com/alixaxel/chrome-aws-lambda/issues/154#issuecomment-664182469,) but unfortunately it didn't help.

`package.json`

```json
"dependencies": {
    "axios": "0.19.2",
    "chrome-aws-lambda": "^5.1.0",
    "get-artist-discography": "0.0.4",
    "puppeteer-core": "^5.1.0",
    "twitter-lite": "0.14.0"
  },
```
`serverless.yml`

```yml
package:
  exclude:
    - chrome-aws-lambda/**
    - node_modules/chrome-aws-lambda/**
    - node_modules/puppeteer/**

functions:
  bot:
    handler: handler.bot
    timeout: 30
    layers:
      - arn:aws:lambda:us-east-1:764866452798:layer:chrome-aws-lambda:19
```

Full Error Message:
```json
{
    "errorType": "Error",
    "errorMessage": "Cannot find module 'puppeteer-core/lib/cjs/common/Browser'\nRequire stack:\n- /opt/nodejs/node_modules/chrome-aws-lambda/source/puppeteer/lib/Browser.js\n- /opt/nodejs/node_modules/chrome-aws-lambda/source/index.js\n- /var/task/handler.js\n- /var/task/s_bot.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    "trace": [
        "Error: Cannot find module 'puppeteer-core/lib/cjs/common/Browser'",
        "Require stack:",
        "- /opt/nodejs/node_modules/chrome-aws-lambda/source/puppeteer/lib/Browser.js",
        "- /opt/nodejs/node_modules/chrome-aws-lambda/source/index.js",
        "- /var/task/handler.js",
        "- /var/task/s_bot.js",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)",
        "    at Module._require.o.require (/var/task/serverless_sdk/index.js:9:89865)",
        "    at require (internal/modules/cjs/helpers.js:72:18)",
        "    at Object.<anonymous> (/opt/nodejs/node_modules/chrome-aws-lambda/source/puppeteer/lib/Browser.js:6:11)",
        "    at Module._compile (internal/modules/cjs/loader.js:1138:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)",
        "    at Module.load (internal/modules/cjs/loader.js:986:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:879:14)",
        "    at Module.require (internal/modules/cjs/loader.js:1026:19)",
        "    at Module._require.o.require (/var/task/serverless_sdk/index.js:9:90125)"
    ]
}{
    "errorType": "Error",
    "errorMessage": "Cannot find module 'puppeteer-core/lib/cjs/common/Browser'\nRequire stack:\n- /opt/nodejs/node_modules/chrome-aws-lambda/source/puppeteer/lib/Browser.js\n- /opt/nodejs/node_modules/chrome-aws-lambda/source/index.js\n- /var/task/handler.js\n- /var/task/s_bot.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    "trace": [
        "Error: Cannot find module 'puppeteer-core/lib/cjs/common/Browser'",
        "Require stack:",
        "- /opt/nodejs/node_modules/chrome-aws-lambda/source/puppeteer/lib/Browser.js",
        "- /opt/nodejs/node_modules/chrome-aws-lambda/source/index.js",
        "- /var/task/handler.js",
        "- /var/task/s_bot.js",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)",
        "    at Module._require.o.require (/var/task/serverless_sdk/index.js:9:89865)",
        "    at require (internal/modules/cjs/helpers.js:72:18)",
        "    at Object.<anonymous> (/opt/nodejs/node_modules/chrome-aws-lambda/source/puppeteer/lib/Browser.js:6:11)",
        "    at Module._compile (internal/modules/cjs/loader.js:1138:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)",
        "    at Module.load (internal/modules/cjs/loader.js:986:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:879:14)",
        "    at Module.require (internal/modules/cjs/loader.js:1026:19)",
        "    at Module._require.o.require (/var/task/serverless_sdk/index.js:9:90125)"
    ]
}
```

**Comment by vladgolubev** [comment]
Hey @metart43 

See this https://github.com/shelfio/chrome-aws-lambda-layer/pull/20#issuecomment-668703515

We're waiting for the issue to be fixed in the chrome-aws-lambda package

**Comment by vladgolubev** [comment]
Try using some older version of layer from here https://github.com/shelfio/chrome-aws-lambda-layer/commits/master/readme.md

**Comment by metart43** [comment]
I am closing the issue in that case
