### ISSUE TITLE
Node 16.x is supported? #275

### ISSUE THREAD

**Issue by outaTiME** [shelfio/chrome-aws-lambda-layer#42]
I am having the following error when I try to run my lambda with node 16.x, does anyone else get this?

```
 "Failed to launch the browser process!\n/tmp/chromium: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory\n\n\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md\n"
```

**Comment by kosanna** [comment]
Have you tried downgrading? Did it work? Going to try with 14 and see if it fixes the issue 🤔

**Comment by vladgolubev** [comment]
Right, this layer depends on https://github.com/alixaxel/chrome-aws-lambda and the upstream repo hasn't been updated to support Node 16 yet.

I see @outaTiME already raise the issue there: https://github.com/alixaxel/chrome-aws-lambda/issues/275

**Comment by vladgolubev** [comment]
I've just published [a new layer version 27 ](https://github.com/shelfio/chrome-aws-lambda-layer/compare/54583aef840ac1a0a3a2574e41ee65f418a1796e...80dfaa1ef6b23fbd343c831b2c5f670675e7f8d7) that has the latest Chromium and Node 16 support!

Thanks again for pointing this out!

**Comment by outaTiME** [comment]
Hi @vladgolubev, for some reason the new layer is not working for me, it throws me the following error:

```
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module '@sparticuz/chrome-aws-lambda'\nRequire stack:\n- /var/task/src/subscribers/social-notify.js\n- /var/runtime/index.mjs",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module '@sparticuz/chrome-aws-lambda'",
        "Require stack:",
        "- /var/task/src/subscribers/social-notify.js",
        "- /var/runtime/index.mjs",
        "    at _loadUserApp (file:///var/runtime/index.mjs:726:17)",
        "    at async Object.module.exports.load (file:///var/runtime/index.mjs:741:21)",
        "    at async file:///var/runtime/index.mjs:781:15",
        "    at async file:///var/runtime/index.mjs:4:1"
    ]
}
```

but if I download the artifact locally (https://github.com/Sparticuz/chrome-aws-lambda/suites/6829349165/artifacts/263061533) and configure it works fine for me, 

it could be that you have left some misconfigured path at the time of your deployment?

**Comment by vladgolubev** [comment]
@outaTiME hm, strange, what I did is just package the same artifact zip as is into a layer

Maybe it's b/c zip has extra `nodejs` folder inside? 

I've just published v28 with that change, could you please try it ?

**Comment by outaTiME** [comment]
Unfortunately using 28 throws the same error, locally my structure for the layer is as follows:

```
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module '@sparticuz/chrome-aws-lambda'\nRequire stack:\n- /var/task/packages/api/src/subscribers/social-notify.js\n- /var/runtime/index.mjs",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module '@sparticuz/chrome-aws-lambda'",
        "Require stack:",
        "- /var/task/packages/api/src/subscribers/social-notify.js",
        "- /var/runtime/index.mjs",
        "    at _loadUserApp (file:///var/runtime/index.mjs:726:17)",
        "    at async Object.module.exports.load (file:///var/runtime/index.mjs:741:21)",
        "    at async file:///var/runtime/index.mjs:781:15",
        "    at async file:///var/runtime/index.mjs:4:1"
    ]
}
```

and as I told you before, I simply unzipped the artifact in a folder called "chrome":

<img width="383" alt="image" src="https://user-images.githubusercontent.com/140472/173363688-5fec3f01-e9e9-41b4-af24-9bf4b001cfaa.png">

I also tell you that I am using SST, I show you a little about the definition of my layer:

```js
const layerArn =
  "arn:aws:lambda:us-east-1:764866452798:layer:chrome-aws-lambda:28";

  socialNotify: {
  function: {
    handler: 'src/subscribers/social-notify.handler',
    bundle: {
      externalModules: ['@sparticuz/chrome-aws-lambda'],
    },
    environment: {
      SOCIAL_SCREENSHOT_URL: quotesSite.url,
    },
    layers: [
      new lambda.LayerVersion(stack, 'ChromeLayer', {
        code: lambda.Code.fromAsset('packages/api/layers/chrome'),
      }),
      // commented out to leave the local layer which is the one that works
      // LayerVersion.fromLayerVersionArn(stack, "ChromeLayer", layerArn),
    ],
    // ~30s
    timeout: '1 minute',
  },
  cdk: {
    subscription: {
      filterPolicy: {
        event: SubscriptionFilter.stringFilter({
          allowlist: ['social-notify'],
        }),
      },
    },
  },
},
```

**Comment by vladgolubev** [comment]
So apparently, embedding `node_modules` inside `nodejs` folder is required, so I reverted that change in the v29.

I'm not familiar with SST so maybe the issue is with it somehow?

**Comment by outaTiME** [comment]
Regardless of SST and the layer has to have the following structure `nodejs/node_modules` (https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html), I just did a download of your layer 28 as follows:

```
$ aws lambda get-layer-version-by-arn --arn "arn:aws:lambda:us-east-1:764866452798:layer:chrome-aws-lambda:28"
```

and looking at the contents I see that the `nodejs` folder does not exist, unlike layer 25, which does have one, I am enclosing a reduced comparison of the contents between both versions:

<img width="685" alt="image" src="https://user-images.githubusercontent.com/140472/173370668-099678f0-a3bd-407b-a08a-398506f2ae4b.png">

**Comment by vladgolubev** [comment]
@outaTiME what about layer version 29? it should have the `nodejs` enclosing folder now.

Thanks for pointing out the dirt. I can see that + some other stuff to be removed (like `.d.ts` files or browser build of libraries)

**Comment by outaTiME** [comment]
Great, I'm trying a new layer 30 as soon as it's available, thanks again !!!

**Comment by outaTiME** [comment]
I just downloaded layer 30, and I keep seeing dirt in the `__MACOSX` folders, could it be?

**Comment by vladgolubev** [comment]
Automated zipping via [create-zip.sh](https://github.com/shelfio/chrome-aws-lambda-layer/blob/master/create-zip.sh) as turns out macOS will create that junk if you zip from UI.

Now it shouldn't be! 

I've published v31 and I don't see any that junk anymore!

<img width="1019" alt="CleanShot 2022-06-13 at 16 59 50@2x" src="https://user-images.githubusercontent.com/3817380/173383456-a499a3df-ffb6-490f-9187-6de264468af9.png">

**Comment by outaTiME** [comment]
sweet, everything works amazing, thanks again @vladgolubev !!!
