### ISSUE TITLE
"The CHROME_PATH environment variable must be set to a Chrome/Chromium executable no older than Chrome stable."

### ISSUE THREAD

**Issue by CraigLager** [shelfio/chrome-aws-lambda-layer#47]
Trying to run lighthouse-cli using this layer and I get the error message 

```
The CHROME_PATH environment variable must be set to a Chrome/Chromium executable no older than Chrome stable.
```

May be because 103.0.5060 has released and the lighthouse package is expecting that?

Lambda configuration:

![image](https://user-images.githubusercontent.com/1162674/179186487-964180cb-c644-4ed6-9984-617b48ccb192.png)

Full error:

```
START RequestId: adba8cc5-ea0b-42e8-9627-668ba45709ad Version: $LATEST
2022-07-15T08:26:47.595Z	adba8cc5-ea0b-42e8-9627-668ba45709ad	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Error: The CHROME_PATH environment variable must be set to a Chrome/Chromium executable no older than Chrome stable.","reason":{"errorType":"Error","errorMessage":"The CHROME_PATH environment variable must be set to a Chrome/Chromium executable no older than Chrome stable.","code":"ERR_LAUNCHER_PATH_NOT_SET","message":"The CHROME_PATH environment variable must be set to a Chrome/Chromium executable no older than Chrome stable.","stack":["Error","    at new LauncherError (/var/task/node_modules/chrome-launcher/dist/utils.js:26:22)","    at new ChromePathNotSetError (/var/task/node_modules/chrome-launcher/dist/utils.js:33:9)","    at Object.linux (/var/task/node_modules/chrome-launcher/dist/chrome-finder.js:128:15)","    at Function.getFirstInstallation (/var/task/node_modules/chrome-launcher/dist/chrome-launcher.js:126:51)","    at Launcher.launch (/var/task/node_modules/chrome-launcher/dist/chrome-launcher.js:185:43)","    at Object.launch (/var/task/node_modules/chrome-launcher/dist/chrome-launcher.js:35:20)","    at runReport (/var/task/index.js:24:39)","    at /var/task/index.js:10:24","    at Array.map (<anonymous>)","    at Runtime.exports.handler (/var/task/index.js:9:36)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: Error: The CHROME_PATH environment variable must be set to a Chrome/Chromium executable no older than Chrome stable.","    at process.<anonymous> (file:///var/runtime/index.mjs:775:15)","    at process.emit (node:events:527:28)","    at process.emit (node:domain:475:12)","    at emit (node:internal/process/promises:140:20)","    at processPromiseRejections (node:internal/process/promises:274:27)","    at processTicksAndRejections (node:internal/process/task_queues:97:32)"]}
[ERROR] [1657873607633] LAMBDA_RUNTIME Failed to post handler success response. Http response code: 403.
END RequestId: adba8cc5-ea0b-42e8-9627-668ba45709ad
REPORT RequestId: adba8cc5-ea0b-42e8-9627-668ba45709ad	Duration: 508.27 ms	Billed Duration: 509 ms	Memory Size: 128 MB	Max Memory Used: 128 MB	Init Duration: 997.19 ms	
RequestId: adba8cc5-ea0b-42e8-9627-668ba45709ad Error: Runtime exited with error: exit status 128
Runtime.ExitError
```

Any tips on resolving this at all?

**Comment by vladgolubev** [comment]
Maybe this could be relevant to you? 

https://github.com/shelfio/chrome-aws-lambda-layer/issues/46#issuecomment-1177412591
