### ISSUE TITLE
version 33 stop working on lambda from 2 day

### ISSUE THREAD

**Issue by neno76** [shelfio/chrome-aws-lambda-layer#66]
Version arn:aws:lambda:eu-central-1:764866452798:layer:chrome-aws-lambda:33 stop working from 2 days in our aws enviroment. 

ERROR	An error occurred while prerendering... Error: Protocol error: Connection closed. Most likely the page has been closed.
    at t.assert (/var/task/handler.js:14:940695)
    at pe.close (/var/task/handler.js:14:835909)
    at g (/var/task/handler.js:2:20392)
    at t.default (/var/task/handler.js:2:18277)
    at s.cb (/var/task/handler.js:2:13765)
    at Object.<anonymous> (/var/task/handler.js:2:45070)

The issues seam the same of  puppeteer-core and @sparticuz/chromium version... but why the issues is now in a oldest version ? Is this version updated in the last 2 days ?

**Comment by neno76** [comment]
I fixed the issue in my production environment, the rendering lambda function use auto update runtime but the last runtime for node16 arn:aws:lambda:eu-central-1::runtime:6821b9edbc91e06f7bfdfbf3387aa97c2df9c7bc80959c565b8c35a8421333ed
broken  puppeteer-core and @sparticuz/chromium, so for fast fix change the runtime to manual il lambda and use the two days old arn:aws:lambda:eu-central-1::runtime:0163909785ec2e11db2b64bb2636ada67bb348dd5764aa83e7eb011bc0f365d8 for me
You can find the previous version in cloudwat with a search for INIT_START on your lambda log

**Comment by krewetka** [comment]
For others if they find themself here -> main issue is here and going to  older image is recommended solution until some fix is done -> https://github.com/Sparticuz/chromium/issues/271#issuecomment-2090949266
